### ISSUE TITLE
Related Observables List Line-Height

### ISSUE THREAD

**Issue by benmontour** [yeti-platform/yeti-feeds-frontend#128]
I'm seeing a line-height issue when looking at the `Related Observables` tab within an observable. It's cutting off the bottom 1/4 of the text. Looking at the element it seems that the line-height of 1.5 is potentially the issue. Increasing this to 2.0 corrects the issue. It seems 2.0 is the value used on say an Entity's `Tagged Observables` tab and elsewhere in the platform. 

![related_observables_line_height](https://github.com/yeti-platform/yeti-feeds-frontend/assets/8712103/f50b48a9-2895-48e0-b9ee-d1ccece2a367)

**Comment by benmontour** [comment]
Forgot to include, this is on version 2.1.0 of the frontend.

**Comment by tomchop** [comment]
Thanks so much for the detailed bug report! (especially when dealing with CSS issues). We'll have a look asap

**Comment by tomchop** [comment]
I looked into this a bit, and... it seems you're still on the old UI? 2.1.0 deprecated the old UI in favor of a brand new Vue3 + Vuetify UI. 

I'm surprised that even on 2.1.0 you're still loading the old UI, but maybe it's just being cached in your browser? Can you try a clear-cache-refresh (Cmd + Shift + R on macOS, Ctrl + Shift + R (I think) on Windows / Linux) and see if that loads the new UI?

**Comment by benmontour** [comment]
You are 100% correct. I'm not sure what happened there, but after updating this is no longer an issue. Sorry about that.
