### ISSUE TITLE
new observers error 

### ISSUE THREAD

**Issue by jax7sec** [yeti-platform/yeti-feeds-frontend#153]
Line 78 of yeti feeds forward \ src \ components \ NewObject. vue,. post (`/api/v2/${this. typeToEndpointMapping [this. newObject. root_type]} ` has an additional '/' which causes a new observers error

**Comment by tomchop** [comment]
I didn't manage to reproduce this. I tried with observable and entity. Can you tell me which object you're trying to create which fails?

**Comment by jax7sec** [comment]
> I didn't manage to reproduce this. I tried with observable and entity. Can you tell me which object you're trying to create which fails?

At line 78 of https://github.com/yeti-platform/yeti-feeds-frontend/blob/main/src/components/NewObject.vue, there is an extra "/" in the URL construction .post(/api/v2/${this.typeToEndpointMapping[this.newObject.root_type]}/ , resulting in a 307 status code error when clicking "new observable" on the frontend. Below is the backend data packet:

POST /api/v2/observables/extended/ HTTP/1.1
Host: x
Accept: application/json, text/plain, /
Accept-Encoding: gzip, deflate
Origin: x
Referer: x
Cookie: yeti_session=x
User-Agent: x
Content-Type: application/json
Content-Length: 48

{"observable":{"type":"ipv4","value":"1.1.1.1"}}
