### ISSUE TITLE
Tags deletion seems to be broken

### ISSUE THREAD

**Issue by udgover** [yeti-platform/yeti-feeds-frontend#80]
From Observable details view, when removing tags and then clicking on save, deleted tags are displayed again in the tags input. After verifying in database, tags are still existing as well.

It could also be related to a misuse of `Observable.tag()`. I was tagging an observable by providing a string instead of a set, resulting to one letter tag.

**Comment by udgover** [comment]
How to reproduce:

from the API, create a new observable and tag with a string from envshell

```
from core.schemas.observables import command_line

cmd_obs = command_line("foobar")
cmd_obs.tag("not_a_set")
```

Then delete / save from UI

**Comment by tomchop** [comment]
Are you calling `save()` on the observable before attempting to tag it?
