### ISSUE TITLE
Link entities and obsersables from UI

### ISSUE THREAD

**Issue by udgover** [yeti-platform/yeti-feeds-frontend#82]
It's possible to link observables and entity via the API but it's not possible from the UI.

Ideally, from the entity details view, it would be nice to bulk select observables and define the link relationship.

**Comment by tomchop** [comment]
How is this different from #81 ?

**Comment by udgover** [comment]
Since the action is not located in the same page (observable details Vs entity details) I thought it would make sense to create two different issues. If that's an implementation which is generic and be added to both views, then I will update #81 and close this one.

**Comment by tomchop** [comment]
Ah I see. Let's wait until we decide about the implementation to dedupe the issues :D

**Comment by tomchop** [comment]
This has been done.
